language: node_js
node_js:
    - "node"
services:
    - mongodb
before_install: npm install -g grunt-cli phantomjs
install: npm install
before_script: grunt init:dev build:dev
after_success:
  - cat ./spec/coverage/reports/lcov.info | ./node_modules/.bin/coveralls --verbose
